export const GET_CAT_ITEMS_REQUEST = 'GET_CAT_ITEMS_REQUEST';
export const GET_CAT_ITEMS_SUCCESS = 'GET_CAT_ITEMS_SUCCESS';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const EDIT_CART_ITEM = 'EDIT_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const SUBMIT_CART_FORM = 'SUBMIT_CART_FORM';